### ISSUE TITLE
Automatically build and publish bottles on formula updates

### ISSUE THREAD

**Issue by mjcheetham** [microsoft/homebrew-git#2]
We should investigate creating a GitHub Actions workflow or Azure Pipelines pipeline to automatically build bottles for updates formulae, and then update the formulae's `bottle do` blocks.

**Comment by derrickstolee** [comment]
Is this done?

**Comment by mjcheetham** [comment]
This is no longer required since we don't have _formulae_ in this tap; they're all casks.
