### ISSUE TITLE
brew install git-credential-manager-core fails in macos

### ISSUE THREAD

**Issue by c4milo** [microsoft/homebrew-git#54]
❯ brew install git-credential-manager-core
==> Downloading https://github.com/GitCredentialManager/git-credential-manager/releases/download/v2.0.632/
Already downloaded: /Users/camiloaguilar/Library/Caches/Homebrew/downloads/bfd79b9cd570ebff2f2d17679303031fe08d706f7839dcbbcac30f6166c18f3b--gcmcore-osx-2.0.632.34631.pkg
==> Installing Cask git-credential-manager-core
==> Running installer for git-credential-manager-core; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcmcore-osx-2.0.632.34631.pkg”.)
==> Purging files for version 2.0.632.34631 of Cask git-credential-manager-core
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=camiloaguilar USER=camiloaguilar USERNAME=camiloaguilar /usr/sbin/installer -pkg /opt/homebrew/Caskroom/git-credential-manager-core/2.0.632.34631/gcmcore-osx-2.0.632.34631.pkg -target / -allowUntrusted` exited with 1. Here's the output:
installer: Package name is Git Credential Manager
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “gcmcore-osx-2.0.632.34631.pkg”.)

**Comment by srhoneGithub** [comment]
I'm facing the same error, did you ever figure out this issue?

**Comment by ldennington** [comment]
@c4milo, @srhoneGithub - sorry for the pain here! We will definitely investigate a fix, but in the meantime, can you try downloading and installing the `.pkg` from our [releases page](https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.779)?

**Comment by objectx** [comment]
Fix released → https://github.com/GitCredentialManager/git-credential-manager/releases/tag/v2.0.785

**Comment by ldennington** [comment]
Closing due to release of fix linked above.
