### ISSUE TITLE
microsoft-git version 2.44.0.vfs.0.1 is broken on Mac

### ISSUE THREAD

**Issue by amrmesbah** [microsoft/homebrew-git#79]
microsoft-git was updated on 3/22 to version 2.44.0.vfs.0.1 which seem to be broken on Mac. After updating git checkout and push fails with the following error message:

% git push
dyld[73077]: Library not loaded: /opt/homebrew/opt/curl/lib/libcurl.4.dylib
Referenced from: <7651D6CC-F49C-3D98-936F-6A41E9C2DCEE> /usr/local/git/libexec/git-core/git-remote-https
Reason: tried: ‘/opt/homebrew/opt/curl/lib/libcurl.4.dylib’ (no such file), ‘/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/curl/lib/libcurl.4.dylib’ (no such file), ‘/opt/homebrew/opt/curl/lib/libcurl.4.dylib’ (no such file)
error: git-remote-https died of signal 6

Curl is explicitly distributed as a keg in brew and calls out the caveat that it can conflict with the version of curl that comes with the OS.

There is no need for git to take a dependency on brew’s curl; we used the install_name_tool to hack the reference back to /usr/lib/libcurl.4.dylib and it works fine.

**Comment by eschwieb** [comment]
See also https://github.com/microsoft/git/issues/634

**Comment by jeffhostetler** [comment]
@amrmesbah @eschwieb 

I have a RC preview release to address this.
https://github.com/microsoft/git/releases/tag/v2.44.0.vfs.0.2.rc0
Please give this a try.

This version does not use Homebrew.

**Comment by jeffhostetler** [comment]
I have published v2.44.0.vfs.0.2 which addresses the problem.  Please try this version.
